import { DashboardStats, Project } from "./types";

export const MOCK_PROJECTS: Project[] = [
  {
    id: "nh-48-surat",
    index: 3,
    name: "NH-48 Rajmarg Extension \u2014 Surat Corridor",
    sector: "National Highway",
    state: "Gujarat",
    district: "Surat",
    lat: 21.1702,
    lng: 72.8311,
    currentStage: "3G",
    areaHectares: 210,
    affectedFamilies: 445,
    rrProgress: 34,
    compensationReady: 41,
    riskLevel: "Critical",
    riskProbability: 99,
    delayMinDays: 79,
    delayMaxDays: 394,
    topRiskFactors: [
      { label: "4 unresolved legal disputes." },
      { label: "Earlier stages averaged 45 days each." },
      { label: "Compensation pending for 59% of affected families." },
      { label: "3G stage is at 3.3x its expected duration." },
    ],
    recommendedActions: [
      { action: "Prioritise compensation verification", owner: "Competent Authority (LA)" },
      { action: "Escalate unresolved cases to the legal cell", owner: "Legal cell" },
      { action: "Schedule a district-level review within seven days", owner: "District Collector" },
      { action: "Assign an additional field officer", owner: "Nodal officer" },
    ],
    modelVersion: "logistic_regression_v1",
    stageHistory: [
      { stage: "3A", enteredOn: "2024-11-02", expectedDays: 30, actualDays: 41 },
      { stage: "3C", enteredOn: "2024-12-13", expectedDays: 45, actualDays: 63 },
      { stage: "3D", enteredOn: "2025-02-14", expectedDays: 40, actualDays: 58 },
      { stage: "3G", enteredOn: "2025-04-13", expectedDays: 60, actualDays: null },
    ],
    alerts: [
      { id: "a1", severity: "Critical", message: "Compensation verification overdue by 61 days at 3G.", raisedOn: "2026-09-10" },
      { id: "a2", severity: "High", message: "4 legal disputes remain unresolved ahead of award.", raisedOn: "2026-09-04" },
    ],
    photos: [{ caption: "Corridor alignment near km 14, Surat bypass" }, { caption: "Compensation camp, Ward 9" }],
    lastUpdated: "2026-09-18",
  },
  {
    id: "nh-44-nagpur",
    index: 1,
    name: "NH-44 Nagpur Bypass \u2014 Package III",
    sector: "National Highway",
    state: "Maharashtra",
    district: "Nagpur",
    lat: 21.1458,
    lng: 79.0882,
    currentStage: "3D",
    areaHectares: 142.5,
    affectedFamilies: 312,
    rrProgress: 48,
    compensationReady: 55,
    riskLevel: "Critical",
    riskProbability: 93,
    delayMinDays: 56,
    delayMaxDays: 157,
    topRiskFactors: [
      { label: "Earlier stages averaged 45 days each." },
      { label: "2 unresolved legal disputes." },
      { label: "3D stage is at 2.9x its expected duration." },
      { label: "Currently at stage 3D." },
    ],
    recommendedActions: [
      { action: "Schedule a district-level review within seven days", owner: "District Collector" },
      { action: "Assign an additional field officer", owner: "Nodal officer" },
      { action: "Accelerate the rehabilitation plan", owner: "R&R administrator" },
      { action: "Follow up on outstanding compensation", owner: "Competent Authority (LA)" },
    ],
    modelVersion: "logistic_regression_v1",
    stageHistory: [
      { stage: "3A", enteredOn: "2025-01-06", expectedDays: 30, actualDays: 33 },
      { stage: "3C", enteredOn: "2025-02-08", expectedDays: 45, actualDays: 52 },
      { stage: "3D", enteredOn: "2025-04-01", expectedDays: 40, actualDays: null },
    ],
    alerts: [
      { id: "a3", severity: "High", message: "Declaration stage running 2.9x its expected duration.", raisedOn: "2026-09-12" },
    ],
    photos: [{ caption: "Bypass Package III, chainage 6+200" }],
    lastUpdated: "2026-09-15",
  },
  {
    id: "nh-27-ayodhya",
    index: 5,
    name: "NH-27 Gorakhpur\u2013Ayodhya Link \u2014 Section B",
    sector: "National Highway",
    state: "Uttar Pradesh",
    district: "Ayodhya",
    lat: 26.7922,
    lng: 82.1998,
    currentStage: "3H",
    areaHectares: 155.2,
    affectedFamilies: 276,
    rrProgress: 61,
    compensationReady: 68,
    riskLevel: "High",
    riskProbability: 64,
    delayMinDays: 47,
    delayMaxDays: 140,
    topRiskFactors: [
      { label: "3H stage is at 9.5x its expected duration." },
      { label: "Earlier stages averaged 45 days each." },
      { label: "1 unresolved legal dispute." },
      { label: "Compensation deposited for 68% of affected families." },
    ],
    recommendedActions: [
      { action: "Expedite pending compensation deposits", owner: "Competent Authority (LA)" },
      { action: "Audit the disbursal backlog at the treasury", owner: "District Collector" },
      { action: "Confirm bank account verification for remaining families", owner: "Nodal officer" },
    ],
    modelVersion: "logistic_regression_v1",
    stageHistory: [
      { stage: "3A", enteredOn: "2024-09-11", expectedDays: 30, actualDays: 34 },
      { stage: "3C", enteredOn: "2024-10-15", expectedDays: 45, actualDays: 49 },
      { stage: "3D", enteredOn: "2024-12-03", expectedDays: 40, actualDays: 44 },
      { stage: "3G", enteredOn: "2025-01-16", expectedDays: 60, actualDays: 58 },
      { stage: "3H", enteredOn: "2025-03-15", expectedDays: 35, actualDays: null },
    ],
    alerts: [
      { id: "a4", severity: "High", message: "Compensation deposit stage far exceeds expected duration.", raisedOn: "2026-09-08" },
    ],
    photos: [{ caption: "Section B right-of-way, near Ayodhya bypass" }],
    lastUpdated: "2026-09-14",
  },
  {
    id: "nh-16-vijayawada",
    index: 4,
    name: "NH-16 Vijayawada Eastern Bypass",
    sector: "National Highway",
    state: "Andhra Pradesh",
    district: "Vijayawada",
    lat: 16.5062,
    lng: 80.648,
    currentStage: "3C",
    areaHectares: 67.8,
    affectedFamilies: 98,
    rrProgress: 72,
    compensationReady: 60,
    riskLevel: "High",
    riskProbability: 50,
    delayMinDays: 34,
    delayMaxDays: 53,
    topRiskFactors: [
      { label: "Earlier stages averaged 45 days each." },
      { label: "Currently at stage 3C." },
      { label: "1 anticipated dispute over valuation." },
    ],
    recommendedActions: [
      { action: "Hold the objection hearing within the statutory window", owner: "District Collector" },
      { action: "Pre-clear the valuation dispute with an independent survey", owner: "Competent Authority (LA)" },
    ],
    modelVersion: "logistic_regression_v1",
    stageHistory: [
      { stage: "3A", enteredOn: "2025-05-02", expectedDays: 30, actualDays: 31 },
      { stage: "3C", enteredOn: "2025-06-02", expectedDays: 45, actualDays: null },
    ],
    alerts: [],
    photos: [{ caption: "Eastern bypass alignment, Vijayawada" }],
    lastUpdated: "2026-09-11",
  },
  {
    id: "nh-19-varanasi",
    index: 6,
    name: "NH-19 Varanasi Ring Road \u2014 Phase 2",
    sector: "National Highway",
    state: "Uttar Pradesh",
    district: "Varanasi",
    lat: 25.3176,
    lng: 82.9739,
    currentStage: "3A",
    areaHectares: 88.4,
    affectedFamilies: 120,
    rrProgress: 12,
    compensationReady: 5,
    riskLevel: "Low",
    riskProbability: 18,
    delayMinDays: 6,
    delayMaxDays: 22,
    topRiskFactors: [
      { label: "No characteristic stands out as elevated versus the portfolio average." },
      { label: "Notification of intent filed on schedule." },
    ],
    recommendedActions: [
      { action: "Continue routine monitoring \u2014 no intervention required", owner: "Nodal officer" },
    ],
    modelVersion: "logistic_regression_v1",
    stageHistory: [{ stage: "3A", enteredOn: "2026-08-20", expectedDays: 30, actualDays: null }],
    alerts: [],
    photos: [{ caption: "Ring road Phase 2 proposed alignment" }],
    lastUpdated: "2026-09-05",
  },
  {
    id: "proposed-prayagraj",
    index: 2,
    name: "Proposed Site \u2014 Prayagraj Vicinity",
    sector: "National Highway",
    state: "Uttar Pradesh",
    district: "Prayagraj",
    lat: 25.397,
    lng: 82.9786,
    currentStage: "3A",
    areaHectares: 45,
    affectedFamilies: 60,
    rrProgress: 0,
    compensationReady: 0,
    riskLevel: "Low",
    riskProbability: 22,
    delayMinDays: 8,
    delayMaxDays: 25,
    topRiskFactors: [{ label: "Assessed prior to notification \u2014 no acquisition activity on record yet." }],
    recommendedActions: [{ action: "Revisit once the notification of intent is filed", owner: "Nodal officer" }],
    modelVersion: "logistic_regression_v1",
    stageHistory: [{ stage: "3A", enteredOn: "2026-09-01", expectedDays: 30, actualDays: null }],
    alerts: [],
    photos: [],
    lastUpdated: "2026-09-01",
  },
];

export function buildDashboardStats(projects: Project[]): DashboardStats {
  const riskDistribution = { Low: 0, Medium: 0, High: 0, Critical: 0 } as DashboardStats["riskDistribution"];
  let land = 0;
  let families = 0;
  let rrSum = 0;
  let needingAttention = 0;

  for (const p of projects) {
    riskDistribution[p.riskLevel]++;
    land += p.areaHectares;
    families += p.affectedFamilies;
    rrSum += p.rrProgress;
    if (p.riskLevel === "High" || p.riskLevel === "Critical") needingAttention++;
  }

  return {
    projectsMonitored: projects.length,
    landUnderAcquisitionHa: Math.round(land * 10) / 10,
    familiesAffected: families,
    meanRrProgress: Math.round(rrSum / projects.length),
    needingAttention,
    riskDistribution,
  };
}
